resilience4j.circuitbreaker:
  instances:
    review-service:
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 4
      minimumNumberOfCalls: 2 #min calls on startup before error rate calc
      failureRateThreshold: 50 #in percentage, Environment ${} variables allowed.
      waitDurationInOpenState: 10s #wait duration
      permittedNumberOfCallsInHalfOpenState: 2
      recordExceptions:
        - org.springframework.web.reactive.function.client.WebClientResponseException
        - java.util.concurrent.TimeoutException